import { Router } from "express";
import { adminAuthRouter } from "./adminAuth.routes.js";
import { adminRouter } from "./admin.routes.js";
import { authRouter } from "./auth.routes.js";
import { adminUsersRouter } from "./adminUsers.routes.js";
import { activitiesRouter } from "./activities.routes.js";
import { appDevicesRouter } from "./appDevices.routes.js";
import { activityContentRouter } from "./activityContent.routes.js";
import { activityRulesRouter } from "./activityRules.routes.js";
import { dailyActivityRouter } from "./dailyActivity.routes.js";
import { dashboardRouter } from "./dashboard.routes.js";
import { eventRegistrationRouter } from "./eventRegistration.routes.js";
import { eventsRouter } from "./events.routes.js";
import { otpVerificationRouter } from "./otpVerification.routes.js";
import { notificationsRouter } from "./notifications.routes.js";
import { pregnancyDayContentRouter } from "./pregnancyDayContent.routes.js";
import { profileRouter } from "./profile.routes.js";
import { pushNotificationLogsRouter } from "./pushNotificationLogs.routes.js";
import { sysRolesRouter } from "./sysRoles.routes.js";
import { sysUserRolesRouter } from "./sysUserRoles.routes.js";
import { sysUsersRouter } from "./sysUsers.routes.js";
import { userEventsRouter } from "./userEvents.routes.js";
import { userPregnancyProfilesRouter } from "./userPregnancyProfiles.routes.js";

const router = Router();

router.use("/admin/auth", adminAuthRouter);
router.use("/admin", adminRouter);
router.use("/auth", authRouter);
router.use("/activities", activitiesRouter);
router.use("/activity-content", activityContentRouter);
router.use("/activity-rules", activityRulesRouter);
router.use("/daily-activities", dailyActivityRouter);
router.use("/dashboard", dashboardRouter);
router.use("/profile", profileRouter);
router.use("/user-events", userEventsRouter);
router.use("/admin-users", adminUsersRouter);
router.use("/app-devices", appDevicesRouter);
router.use("/event-registrations", eventRegistrationRouter);
router.use("/events", eventsRouter);
router.use("/otp-verifications", otpVerificationRouter);
router.use("/notifications", notificationsRouter);
router.use("/pregnancy-day-content", pregnancyDayContentRouter);
router.use("/push-notification-logs", pushNotificationLogsRouter);
router.use("/sys-roles", sysRolesRouter);
router.use("/sys-user-roles", sysUserRolesRouter);
router.use("/sys-users", sysUsersRouter);
router.use("/user-pregnancy-profiles", userPregnancyProfilesRouter);

export const apiRouter = router;
