import { z } from "zod";

const uuid = z.uuid();
const shortText = (max) => z.string().trim().min(1).max(max);
const text = () => z.string().trim().min(1);
const nullableText = (max) => z.string().trim().max(max).optional().nullable();
const nullableLongText = () => z.string().trim().optional().nullable();
const nullableBool = z.boolean().optional().nullable();
const int = z.coerce.number().int();
const nullableInt = z.coerce.number().int().optional().nullable();
const timestamp = z.coerce.date();
const nullableTimestamp = z.coerce.date().optional().nullable();
const dateOnly = z.coerce.date();

export const modelDefinitions = {
  admin_users: {
    model: "admin_users",
    path: "admin-users",
    label: "Admin user",
    labelPlural: "Admin users",
    fields: {
      id: { schema: uuid },
      name: { schema: shortText(100), required: true },
      email: { schema: z.email().max(150), required: true },
      password_hash: { schema: shortText(255), required: true },
      role: { schema: shortText(50), required: true },
      is_active: { schema: nullableBool },
      created_at: { schema: nullableTimestamp, readOnly: true },
    },
  },
  app_devices: {
    model: "app_devices",
    path: "app-devices",
    label: "App device",
    labelPlural: "App devices",
    fields: {
      id: { schema: uuid },
      device_id: { schema: shortText(255), required: true },
      device_type: { schema: shortText(50), required: true },
      app_version: { schema: nullableText(20) },
      push_token: { schema: nullableLongText() },
      notification_enabled: { schema: nullableBool },
      push_token_updated_at: { schema: nullableTimestamp },
      trial_started_at: { schema: timestamp, required: true },
      trial_expires_at: { schema: timestamp, required: true },
      converted_to_user: { schema: nullableBool },
      user_id: { schema: uuid.optional().nullable() },
      created_at: { schema: nullableTimestamp, readOnly: true },
    },
  },
  event_registration: {
    model: "event_registration",
    path: "event-registrations",
    label: "Event registration",
    labelPlural: "Event registrations",
    fields: {
      id: { schema: uuid },
      user_id: { schema: uuid, required: true },
      event_id: { schema: uuid, required: true },
      registered_at: { schema: nullableTimestamp },
    },
  },
  events: {
    model: "events",
    path: "events",
    label: "Event",
    labelPlural: "Events",
    fields: {
      id: { schema: uuid },
      title: { schema: shortText(255), required: true },
      description: { schema: text(), required: true },
      event_date: { schema: timestamp, required: true },
      start_time: { schema: nullableTimestamp },
      end_time: { schema: nullableTimestamp },
      program_name: { schema: nullableText(255) },
      address: { schema: nullableLongText() },
      state: { schema: nullableText(100) },
      city: { schema: nullableText(100) },
      pincode: { schema: nullableText(20) },
      gallery: { schema: nullableLongText() },
      role: { schema: nullableText(100) },
      legacy_user_id: { schema: nullableText(100) },
      remark: { schema: nullableLongText() },
      contact_person: { schema: nullableText(100) },
      webinar_url: { schema: nullableLongText() },
      webinar_password: { schema: nullableLongText() },
      status: { schema: nullableText(20) },
      comment_reply: { schema: nullableLongText() },
      join_link: { schema: nullableLongText() },
      is_active: { schema: nullableBool },
      created_at: { schema: nullableTimestamp, readOnly: true },
      updated_at: { schema: nullableTimestamp },
    },
  },
  otp_verification: {
    model: "otp_verification",
    path: "otp-verifications",
    label: "OTP verification",
    labelPlural: "OTP verifications",
    fields: {
      id: { schema: uuid },
      phone_number: { schema: shortText(15), required: true },
      otp_code: { schema: shortText(6), required: true },
      is_verified: { schema: nullableBool },
      expires_at: { schema: timestamp, required: true },
      created_at: { schema: nullableTimestamp, readOnly: true },
    },
  },
  pregnancy_day_content: {
    model: "pregnancy_day_content",
    path: "pregnancy-day-content",
    label: "Pregnancy day content",
    labelPlural: "Pregnancy day content",
    fields: {
      id: { schema: uuid },
      day_number: { schema: int, required: true },
      meditation_title: { schema: nullableText(255) },
      meditation_url: { schema: nullableLongText() },
      music_url: { schema: nullableLongText() },
      youtube_video_url: { schema: nullableLongText() },
      reading_content: { schema: nullableLongText() },
      affirmation: { schema: nullableLongText() },
      tips: { schema: nullableLongText() },
      created_at: { schema: nullableTimestamp, readOnly: true },
      updated_at: { schema: nullableTimestamp },
    },
  },
  push_notification_logs: {
    model: "push_notification_logs",
    path: "push-notification-logs",
    label: "Push notification log",
    labelPlural: "Push notification logs",
    fields: {
      id: { schema: uuid },
      user_id: { schema: uuid, required: true },
      type: { schema: shortText(50), required: true },
      sent_at: { schema: timestamp, required: true },
      status: { schema: shortText(50), required: true },
    },
  },
  sys_roles: {
    model: "sys_roles",
    path: "sys-roles",
    label: "System role",
    labelPlural: "System roles",
    fields: {
      id: { schema: uuid },
      role_name: { schema: shortText(50), required: true },
      role_code: { schema: shortText(50), required: true },
      description: { schema: nullableLongText() },
      converted_user_id: { schema: uuid.optional().nullable() },
      created_at: { schema: nullableTimestamp, readOnly: true },
    },
  },
  sys_user_roles: {
    model: "sys_user_roles",
    path: "sys-user-roles",
    label: "System user role",
    labelPlural: "System user roles",
    fields: {
      id: { schema: uuid },
      user_id: { schema: uuid, required: true },
      role_id: { schema: uuid, required: true },
      assigned_at: { schema: nullableTimestamp },
      is_verified: { schema: nullableBool },
      created_at: { schema: nullableTimestamp, readOnly: true },
    },
  },
  sys_users: {
    model: "sys_users",
    path: "sys-users",
    label: "System user",
    labelPlural: "System users",
    fields: {
      id: { schema: uuid },
      full_name: { schema: shortText(100), required: true },
      phone_number: { schema: shortText(15), required: true },
      email: { schema: z.email().max(150).optional().nullable() },
      password_hash: { schema: text(), required: true },
      device_id: { schema: shortText(255), required: true },
      is_active: { schema: nullableBool },
      created_at: { schema: nullableTimestamp, readOnly: true },
      updated_at: { schema: nullableTimestamp },
    },
  },
  user_pregnancy_profiles: {
    model: "user_pregnancy_profiles",
    path: "user-pregnancy-profiles",
    label: "User pregnancy profile",
    labelPlural: "User pregnancy profiles",
    fields: {
      id: { schema: uuid },
      user_id: { schema: uuid, required: true },
      pregnancy_start_date: { schema: dateOnly, required: true },
      due_date: { schema: dateOnly, required: true },
      current_week: { schema: nullableInt },
      current_day: { schema: nullableInt },
      baby_name: { schema: nullableText(100) },
      doctor_name: { schema: nullableText(150) },
      hospital_name: { schema: nullableText(150) },
      created_at: { schema: nullableTimestamp, readOnly: true },
      updated_at: { schema: nullableTimestamp },
    },
  },
};
